### ISSUE TITLE
feat(tes & design): improve bundling

### ISSUE THREAD

**Issue by git-anurag-hub** [elixir-cloud-aai/cloud-components#138]
## Description

Right now Design & TES are using tsup to generate the build the problem is that there is only one file generated globally in the build. Apply tree shaking to it so that the user can import the individual components & reduce there overall build size & loading time. Tree shaking is a popular solution for that & can be implemented in tsup like this https://tsup.egoist.dev/#tree-shaking

### Tasks
- [x]  Code splitting and declaration files generation -  #167 
- [ ] Add shoelace assets entry point
- [ ] Build cdn package
- [ ] Add support for React

**Comment by SalihuDickson** [comment]
We might want to look into writing custom scripts. Especially considering there is no bundler that will build our components to support React out of the box.

**Comment by SalihuDickson** [comment]
@git-anurag-hub, I'll go ahead and write a build script using that as a reference, i should be able to get the code splitting to work properly.
